kind = "mobile"
previewPath = "/"
title = "Самозванец"
version = "1.0.0"
id = "artifacts/find-imposter"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23482

[services.development]
run = "pnpm --filter @workspace/find-imposter run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/find-imposter", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/find-imposter", "run", "serve" ]

[services.env]
PORT = "23482"
BASE_PATH = "/"
